window.SITE_SEARCH_INDEX = [
  {"title": "About British TV Hub | The Story", "url": "/about.html"},
  {"title": "What's New on Acorn TV", "url": "/acorn.html"},
  {"title": "British TV Actors in Multiple Mystery Shows", "url": "/actor-crossovers.html"},
  {"title": "Agatha Christie's Spookiest Mysteries", "url": "/agatha-christie-spooky-mysteries.html"},
  {"title": "Agatha Christie TV Adaptations Guide", "url": "/agatha-christie.html"},
  {"title": "Ann Cleeves Books in Order", "url": "/ann-cleeves.html"},
  {"title": "Cozy Autumn Gifts for British TV Fans", "url": "/autumn-gift-guide.html"},
  {"title": "Best British Cozy Mysteries to Read Now", "url": "/best-british-cozy-mysteries.html"},
  {"title": "Best British Mysteries on Acorn TV (2026)", "url": "/best-british-mysteries-on-acorn-tv.html"},
  {"title": "25 Best British Mystery Shows for 2026", "url": "/best-british-mystery-shows-2026.html"},
  {"title": "Best Cozy Mystery Authors", "url": "/best-cozy-mystery-authors.html"},
  {"title": "Books Like Midsomer Murders", "url": "/books-like-midsomer-murders.html"},
  {"title": "Books Like Vera: What to Read Next", "url": "/books-like-vera.html"},
  {"title": "British Mystery Books & TV Adaptations", "url": "/books.html"},
  {"title": "What's New on BritBox", "url": "/britbox.html"},
  {"title": "Best British Crime Dramas", "url": "/british-crime-dramas.html"},
  {"title": "11 Best British Female TV Detectives", "url": "/british-female-detectives.html"},
  {"title": "British Historical Fiction Books", "url": "/british-historical-fiction-books.html"},
  {"title": "British Period Dramas", "url": "/british-period-dramas.html"},
  {"title": "British TV Acronyms Explained", "url": "/british-tv-acronyms-explained.html"},
  {"title": "What's Your British TV Personality?", "url": "/british-tv-personality-quiz.html"},
  {"title": "Classic British Detective Shows", "url": "/classic-british-detective-shows.html"},
  {"title": "Classic British TV", "url": "/classic-british-tv.html"},
  {"title": "Collections: British TV Themed Guides", "url": "/collections.html"},
  {"title": "Share a Gift Idea | Community", "url": "/community-snug.html"},
  {"title": "Murder at the Manor: British Country-House Mysteries", "url": "/country-house-mysteries.html"},
  {"title": "Cozy Autumn Mysteries", "url": "/cozy-autumn-mysteries.html"},
  {"title": "Cozy Mystery Detectives", "url": "/cozy-mystery-detectives.html"},
  {"title": "Cozy Mystery Settings", "url": "/cozy-mystery-settings.html"},
  {"title": "Best Cozy British Mystery Shows", "url": "/cozy.html"},
  {"title": "British Crime & Police Drama Hub", "url": "/crime-drama-hub.html"},
  {"title": "13 British Mysteries for October Nights", "url": "/dark-october-night-mysteries.html"},
  {"title": "British Detective Partnerships", "url": "/detective-partnerships.html"},
  {"title": "If You Love Downton Abbey, Read These Books", "url": "/downton-abbey-books.html"},
  {"title": "Shop by Theme: Curated Collections", "url": "/essentials-collections.html"},
  {"title": "Cozy Corner | The Snug", "url": "/essentials-cozy.html"},
  {"title": "Read: Books Behind the Shows | The Snug", "url": "/essentials-read.html"},
  {"title": "Watch: British Mysteries on DVD | The Snug", "url": "/essentials-watch.html"},
  {"title": "British TV Essentials", "url": "/essentials.html"},
  {"title": "Autumn 2026 TV Preview", "url": "/fall-preview-2026.html"},
  {"title": "British Family Sagas: TV Shows & Books", "url": "/family-sagas.html"},
  {"title": "British TV FAQ: BritBox, Acorn TV & More", "url": "/faq.html"},
  {"title": "Where the Mystery Began, Part 2", "url": "/first-books-2.html"},
  {"title": "Where the Mystery Began: First Books", "url": "/first-books.html"},
  {"title": "British TV by Genre", "url": "/genres.html"},
  {"title": "A Ghost Story for Halloween", "url": "/ghost-story-for-halloween.html"},
  {"title": "Gifts for British TV Fans: All Gift Guides", "url": "/gift-guide-hub.html"},
  {"title": "British TV Gift Ideas: Shop Fan Favourites", "url": "/gift-ideas.html"},
  {"title": "Golden Age Mystery: Christie, Sayers & Tey", "url": "/golden-age-mystery.html"},
  {"title": "Build Your Perfect British Halloween Mystery", "url": "/halloween-mystery-builder.html"},
  {"title": "Happy Valley Season Guide", "url": "/happy-valley-season-guide.html"},
  {"title": "Hidden British Dramas", "url": "/hidden-dramas.html"},
  {"title": "Hidden Gem British TV Shows", "url": "/hidden-gems.html"},
  {"title": "Holiday Gifts for British TV & Mystery Fans", "url": "/holiday-gift-guide.html"},
  {"title": "Holiday Guide: What to Watch (2026)", "url": "/holiday-guide-watch.html"},
  {"title": "Holiday Guide: Specials Collection", "url": "/holiday-specials.html"},
  {"title": "Inspector Morse Books: Reading Guide", "url": "/inspector-morse-books.html"},
  {"title": "Best Episodes of Inspector Morse, Ranked", "url": "/inspector-morse-episodes-ranked.html"},
  {"title": "New to Line of Duty? A Beginner's Guide", "url": "/line-of-duty-beginners-guide.html"},
  {"title": "The Best Episodes of Line of Duty, Ranked", "url": "/line-of-duty-episode-ranker.html"},
  {"title": "Line of Duty: Under Investigation", "url": "/line-of-duty-guest-stars.html"},
  {"title": "Best Line of Duty Seasons, Ranked (Series 1–6)", "url": "/line-of-duty-series-ranked.html"},
  {"title": "What's on PBS Masterpiece", "url": "/masterpiece2026.html"},
  {"title": "Meet Tilly", "url": "/meet-tilly.html"},
  {"title": "The British TV Hub Collection | Mugs, Journals & More", "url": "/merch.html"},
  {"title": "New to Midsomer Murders? A Beginner's Guide", "url": "/midsomer-murders-beginners-guide.html"},
  {"title": "Rank Midsomer Murders Episodes", "url": "/midsomer-murders-episode-ranker.html"},
  {"title": "Midsomer Murders Filming Locations", "url": "/midsomer-murders-filming-locations.html"},
  {"title": "The Best Episodes of Miss Marple, Ranked", "url": "/miss-marple-episode-ranker.html"},
  {"title": "Modern Crime Procedurals", "url": "/modern-crime-procedurals.html"},
  {"title": "Sunday Picks Newsletter Archive", "url": "/newsletter-archive.html"},
  {"title": "Cancelled British Shows: What Next", "url": "/now-that-its-ended.html"},
  {"title": "British Mysteries: Page to Screen", "url": "/page-to-screen.html"},
  {"title": "Partner With Us", "url": "/partner.html"},
  {"title": "Poirot Books: The Complete Reading Guide", "url": "/poirot-books.html"},
  {"title": "Best Seasons of Poirot, Ranked", "url": "/poirot-dvds.html"},
  {"title": "Modern Police Procedurals", "url": "/police-procedurals.html"},
  {"title": "Privacy Policy", "url": "/privacy.html"},
  {"title": "Match Me a Mystery Quiz", "url": "/quiz.html"},
  {"title": "British TV Games & Quizzes", "url": "/quizzes-and-games.html"},
  {"title": "Rainy Day Mysteries", "url": "/rainy-day-mysteries.html"},
  {"title": "Richard Osman Books in Order", "url": "/richard-osman.html"},
  {"title": "Season Preview: New British TV", "url": "/season-preview.html"},
  {"title": "Seasonal Collections", "url": "/seasonal-collections.html"},
  {"title": "Share British TV Hub With a Friend", "url": "/share-with-a-friend.html"},
  {"title": "Shetland Books: The Complete Reading Guide", "url": "/shetland-books.html"},
  {"title": "The Best Seasons of Shetland, Ranked", "url": "/shetland-dvds.html"},
  {"title": "CozyTVCompanion Shop", "url": "/shop.html"},
  {"title": "Browse British TV Shows: Complete Index", "url": "/shows-index.html"},
  {"title": "8 Shows Like Agatha Raisin", "url": "/shows-like-agatha-raisin-tv.html"},
  {"title": "Shows Like All Creatures Great & Small", "url": "/shows-like-all-creatures-great-and-small-tv.html"},
  {"title": "8 Shows Like Beyond Paradise", "url": "/shows-like-beyond-paradise-tv.html"},
  {"title": "8 Shows Like Blue Lights on BritBox", "url": "/shows-like-blue-lights-tv.html"},
  {"title": "Shows Like Broadchurch: What to Watch Next", "url": "/shows-like-broadchurch-tv.html"},
  {"title": "8 Shows Like Call the Midwife", "url": "/shows-like-call-the-midwife-tv.html"},
  {"title": "Shows Like Death in Paradise", "url": "/shows-like-death-in-paradise-tv.html"},
  {"title": "8 Shows Like Doc Martin", "url": "/shows-like-doc-martin-tv.html"},
  {"title": "Shows Like Downton Abbey", "url": "/shows-like-downton-abbey-tv.html"},
  {"title": "5 Shows Like Endeavour to Watch Next", "url": "/shows-like-endeavour-tv.html"},
  {"title": "Shows Like Father Brown: What to Watch Next", "url": "/shows-like-father-brown-tv.html"},
  {"title": "8 Shows Like Foyle's War", "url": "/shows-like-foyles-war-tv.html"},
  {"title": "Shows Like Grantchester: What to Watch Next", "url": "/shows-like-grantchester-tv.html"},
  {"title": "Shows Like Happy Valley: What to Watch Next", "url": "/shows-like-happy-valley-tv.html"},
  {"title": "Shows Like Inspector Morse", "url": "/shows-like-inspector-morse-tv.html"},
  {"title": "8 Shows Like Lewis", "url": "/shows-like-lewis-tv.html"},
  {"title": "8 Shows Like Line of Duty: Tense British Police Dramas", "url": "/shows-like-line-of-duty-tv.html"},
  {"title": "8 Shows Like Ludwig", "url": "/shows-like-ludwig-tv.html"},
  {"title": "8 Shows Like Marble Hall Murders", "url": "/shows-like-marble-hall-murders-tv.html"},
  {"title": "8 Shows Like Marlow Murder Club to Watch", "url": "/shows-like-marlow-murder-club-tv.html"},
  {"title": "Shows Like Midsomer Murders", "url": "/shows-like-midsomer-murders-tv.html"},
  {"title": "8 Shows Like Miss Marple to Watch Next", "url": "/shows-like-miss-marple-tv.html"},
  {"title": "Shows Like Poirot: What to Watch Next", "url": "/shows-like-poirot-tv.html"},
  {"title": "8 Shows Like Rosemary & Thyme", "url": "/shows-like-rosemary-and-thyme-tv.html"},
  {"title": "Shows Like Sherlock: What to Watch Next", "url": "/shows-like-sherlock-tv.html"},
  {"title": "8 Shows Like Shetland to Watch Next", "url": "/shows-like-shetland-tv.html"},
  {"title": "8 Shows Like Unforgotten to Watch Next", "url": "/shows-like-unforgotten-tv.html"},
  {"title": "9 Shows Like Vera to Watch Next", "url": "/shows-like-vera-tv.html"},
  {"title": "Shows Like Vera, Downton Abbey & More", "url": "/shows-like.html"},
  {"title": "10 British TV Shows That Feel Like a Warm Blanket", "url": "/shows-that-feel-like-a-warm-blanket.html"},
  {"title": "Best British Mystery & Drama Shows", "url": "/shows.html"},
  {"title": "Agatha Raisin: Where to Watch in the US", "url": "/shows/agatha-raisin.html"},
  {"title": "All Creatures Great and Small", "url": "/shows/all-creatures-great-and-small.html"},
  {"title": "Art Detectives: Where to Watch in the US", "url": "/shows/art-detectives.html"},
  {"title": "Beyond Paradise: Where to Watch in the US", "url": "/shows/beyond-paradise.html"},
  {"title": "Blue Lights", "url": "/shows/blue-lights.html"},
  {"title": "Blue Murder Motel: Where to Watch in the US", "url": "/shows/blue-murder-motel.html"},
  {"title": "Bookish: Where to Watch in the US", "url": "/shows/bookish.html"},
  {"title": "Broadchurch: Where to Watch in the US", "url": "/shows/broadchurch.html"},
  {"title": "Call the Midwife", "url": "/shows/call-the-midwife.html"},
  {"title": "Cooper and Fry: Where to Watch in the US", "url": "/shows/cooper-and-fry.html"},
  {"title": "Dalgliesh: Where to Watch in the US", "url": "/shows/dalgliesh.html"},
  {"title": "Death in Paradise", "url": "/shows/death-in-paradise.html"},
  {"title": "Death Valley Season 2: Where to Watch", "url": "/shows/death-valley.html"},
  {"title": "Doc Martin", "url": "/shows/doc-martin.html"},
  {"title": "Endeavour: Where to Watch in the US", "url": "/shows/endeavour.html"},
  {"title": "Father Brown: Where to Watch in the US", "url": "/shows/father-brown.html"},
  {"title": "Foyle's War: Where to Watch in the US", "url": "/shows/foyles-war.html"},
  {"title": "Grace: Where to Watch in the US", "url": "/shows/grace.html"},
  {"title": "Grantchester", "url": "/shows/grantchester.html"},
  {"title": "Happy Valley", "url": "/shows/happy-valley.html"},
  {"title": "Home Fires", "url": "/shows/home-fires.html"},
  {"title": "Inspector Morse", "url": "/shows/inspector-morse.html"},
  {"title": "Lewis: Where to Watch in the US", "url": "/shows/lewis.html"},
  {"title": "Line of Duty", "url": "/shows/line-of-duty.html"},
  {"title": "Little Women", "url": "/shows/little-women.html"},
  {"title": "Ludwig", "url": "/shows/ludwig.html"},
  {"title": "Lynley: Where to Watch in the US", "url": "/shows/lynley.html"},
  {"title": "Maigret Season 2: Where to Watch", "url": "/shows/maigret.html"},
  {"title": "Marble Hall Murders: Where to Watch", "url": "/shows/marble-hall-murders.html"},
  {"title": "The Marlow Murder Club", "url": "/shows/marlow-murder-club.html"},
  {"title": "Midsomer Murders", "url": "/shows/midsomer-murders.html"},
  {"title": "Miss Marple", "url": "/shows/miss-marple.html"},
  {"title": "Poirot: Where to Watch in the US", "url": "/shows/poirot.html"},
  {"title": "Poldark", "url": "/shows/poldark.html"},
  {"title": "Professor T", "url": "/shows/professor-t.html"},
  {"title": "Return to Paradise: Where to Watch", "url": "/shows/return-to-paradise.html"},
  {"title": "Sanditon", "url": "/shows/sanditon.html"},
  {"title": "Sherlock", "url": "/shows/sherlock.html"},
  {"title": "Sherwood: Where to Watch the BBC Mining Village Crime Drama", "url": "/shows/sherwood.html"},
  {"title": "Shetland", "url": "/shows/shetland.html"},
  {"title": "Signora Volpe: Where to Watch in the US", "url": "/shows/signora-volpe.html"},
  {"title": "Silent Witness: Where to Watch in the US", "url": "/shows/silent-witness.html"},
  {"title": "The Assassin: Where to Watch in the US", "url": "/shows/the-assassin.html"},
  {"title": "The Chelsea Detective: Where to Watch", "url": "/shows/the-chelsea-detective.html"},
  {"title": "The Durrells in Corfu", "url": "/shows/the-durrells-in-corfu.html"},
  {"title": "The Gold Season 2: Where to Watch", "url": "/shows/the-gold.html"},
  {"title": "Time — Season 3: Where to Watch in the US", "url": "/shows/time.html"},
  {"title": "Agatha Christie's Tommy & Tuppence", "url": "/shows/tommy-and-tuppence.html"},
  {"title": "Trespasses on PBS Masterpiece: Where to Watch in the US", "url": "/shows/trespasses.html"},
  {"title": "Trigger Point", "url": "/shows/trigger-point.html"},
  {"title": "Unforgotten", "url": "/shows/unforgotten.html"},
  {"title": "Vera", "url": "/shows/vera.html"},
  {"title": "Victoria", "url": "/shows/victoria.html"},
  {"title": "So You Think You've Seen It All?", "url": "/so-you-think-youve-seen-it-all.html"},
  {"title": "New to British TV? Start Here", "url": "/start-here.html"},
  {"title": "Where to Watch British TV in the US", "url": "/streaming.html"},
  {"title": "5 Best British Sunday Night Dramas", "url": "/sunday-night-dramas.html"},
  {"title": "Create Your Ideal Sunday-Night Lineup", "url": "/sunday-night-lineup.html"},
  {"title": "Support British TV Hub | Help Keep the Kettle On", "url": "/support.html"},
  {"title": "Tartan Noir: Scotland's Crime Fiction", "url": "/tartan-noir.html"},
  {"title": "Tense British Crime Dramas to Watch", "url": "/tense-british-crime-drama.html"},
  {"title": "The Cozy Collection", "url": "/the-cozy-collection.html"},
  {"title": "Things British TV Has Taught Me", "url": "/things-british-tv-has-taught-me.html"},
  {"title": "This Week in British TV: New Premieres", "url": "/this-week.html"},
  {"title": "Best British Police Procedurals", "url": "/top10.html"},
  {"title": "New to Vera? A Beginner's Guide", "url": "/vera-beginners-guide.html"},
  {"title": "Which Cozy English Village Are You?", "url": "/village-quiz.html"},
  {"title": "Your Watch List", "url": "/watch-list.html"},
  {"title": "Weekend Binge Guide: Short British Series", "url": "/weekend-binge-guide.html"},
  {"title": "What Are You Watching?", "url": "/what-are-you-watching.html"},
  {"title": "Who Outranks Who? British Detective Ranks", "url": "/who-outranks-who.html"},
  {"title": "Why British TV Feels Cozy", "url": "/why-british-tv-feels-cozy.html"},
  {"title": "Search Every Show British TV Hub Tracks", "url": "/shows-index.html#full-database-search"},
  {"title": "British TV Hub Home", "url": "/"}
];
