window.SITE_SEARCH_INDEX = [
  {"title":"About British TV Hub | Our Story","url":"/about.html"},
  {"title":"What's New on Acorn TV","url":"/acorn.html"},
  {"title":"Agatha Christie TV Adaptations Guide","url":"/agatha-christie.html"},
  {"title":"Ann Cleeves Books in Order","url":"/ann-cleeves.html"},
  {"title":"British Mystery Shows for Beginners","url":"/beginners.html"},
  {"title":"Best British Cozy Mysteries to Read Now","url":"/best-british-cozy-mysteries.html"},
  {"title":"Books Like Midsomer Murders","url":"/books-like-midsomer-murders.html"},
  {"title":"Books Like Vera: What to Read Next","url":"/books-like-vera.html"},
  {"title":"British Mystery Books & TV Adaptations","url":"/books.html"},
  {"title":"What's New on BritBox","url":"/britbox.html"},
  {"title":"British Historical Fiction Books","url":"/british-historical-fiction-books.html"},
  {"title":"Who Outranks Who? British Detective Ranks","url":"/who-outranks-who.html"},
  {"title":"British TV Acronyms Explained","url":"/british-tv-acronyms-explained.html"},
  {"title":"Cozy Mystery Settings","url":"/cozy-mystery-settings.html"},
  {"title":"Cozy Mystery Detectives","url":"/cozy-mystery-detectives.html"},
  {"title":"Why British TV Feels Cozy","url":"/why-british-tv-feels-cozy.html"},
  {"title":"Best Cozy British Mystery Shows","url":"/cozy.html"},
  {"title":"If You Love Downton Abbey, Read These Books","url":"/downton-abbey-books.html"},
  {"title":"British TV Essentials","url":"/essentials.html"},
  {"title":"British TV FAQ: BritBox, Acorn TV & More","url":"/faq.html"},
  {"title":"What's on PBS Masterpiece","url":"/masterpiece2026.html"},
  {"title":"Meet Tilly","url":"/meet-tilly.html"},
  {"title":"Partner With Us","url":"/partner.html"},
  {"title":"Match Me a Mystery Quiz","url":"/quiz.html"},
  {"title":"Richard Osman Books in Order","url":"/richard-osman.html"},
  {"title":"CozyTVCompanion Shop","url":"/shop.html"},
  {"title":"Browse British TV Shows: Complete Index","url":"/shows-index.html"},
  {"title":"Best British Mystery & Drama Shows","url":"/shows.html"},
  {"title":"All Creatures Great and Small","url":"/shows/all-creatures-great-and-small.html"},
  {"title":"Blue Lights","url":"/shows/blue-lights.html"},
  {"title":"Call the Midwife","url":"/shows/call-the-midwife.html"},
  {"title":"Death in Paradise","url":"/shows/death-in-paradise.html"},
  {"title":"Doc Martin","url":"/shows/doc-martin.html"},
  {"title":"Grantchester","url":"/shows/grantchester.html"},
  {"title":"Happy Valley","url":"/shows/happy-valley.html"},
  {"title":"Home Fires","url":"/shows/home-fires.html"},
  {"title":"Inspector Morse","url":"/shows/inspector-morse.html"},
  {"title":"Line of Duty","url":"/shows/line-of-duty.html"},
  {"title":"Little Women","url":"/shows/little-women.html"},
  {"title":"Ludwig","url":"/shows/ludwig.html"},
  {"title":"The Marlow Murder Club","url":"/shows/marlow-murder-club.html"},
  {"title":"Midsomer Murders","url":"/shows/midsomer-murders.html"},
  {"title":"Miss Marple","url":"/shows/miss-marple.html"},
  {"title":"Poldark","url":"/shows/poldark.html"},
  {"title":"Professor T","url":"/shows/professor-t.html"},
  {"title":"Sanditon","url":"/shows/sanditon.html"},
  {"title":"Sherlock","url":"/shows/sherlock.html"},
  {"title":"Shetland","url":"/shows/shetland.html"},
  {"title":"The Durrells in Corfu","url":"/shows/the-durrells-in-corfu.html"},
  {"title":"Agatha Christie's Tommy & Tuppence","url":"/shows/tommy-and-tuppence.html"},
  {"title":"Trigger Point","url":"/shows/trigger-point.html"},
  {"title":"Unforgotten","url":"/shows/unforgotten.html"},
  {"title":"Vera","url":"/shows/vera.html"},
  {"title":"Victoria","url":"/shows/victoria.html"},
  {"title":"Where to Watch British TV in the US","url":"/streaming.html"},
  {"title":"Search Every Show We Track","url":"/shows-index.html#full-database-search"},
  {"title":"Best British Police Procedurals","url":"/top10.html"}
];
