/* Maps show-database titles to their guide page slug (/shows/<slug>.html). Used by the Watch List and the subscription finder so a show tracked anywhere uses one key. Add a line when a new show guide page is published. */
window.BTVH_GUIDES = {
  "Agatha Raisin": "agatha-raisin",
  "All Creatures Great and Small": "all-creatures-great-and-small",
  "Art Detectives": "art-detectives",
  "Beyond Paradise": "beyond-paradise",
  "Blue Lights": "blue-lights",
  "Blue Murder Motel": "blue-murder-motel",
  "Bookish": "bookish",
  "Broadchurch": "broadchurch",
  "Call the Midwife": "call-the-midwife",
  "Cooper & Fry": "cooper-and-fry",
  "Dalgliesh": "dalgliesh",
  "Death in Paradise": "death-in-paradise",
  "Death Valley": "death-valley",
  "Doc Martin": "doc-martin",
  "Endeavour": "endeavour",
  "Father Brown": "father-brown",
  "Foyle's War": "foyles-war",
  "Grace": "grace",
  "Grantchester": "grantchester",
  "Happy Valley": "happy-valley",
  "Home Fires": "home-fires",
  "Inspector Morse": "inspector-morse",
  "Lewis": "lewis",
  "Line of Duty": "line-of-duty",
  "Little Women": "little-women",
  "Ludwig": "ludwig",
  "Lynley": "lynley",
  "Maigret (2025)": "maigret",
  "Marble Hall Murders": "marble-hall-murders",
  "The Marlow Murder Club": "marlow-murder-club",
  "Midsomer Murders": "midsomer-murders",
  "Agatha Christie's Poirot": "poirot",
  "Poldark": "poldark",
  "Professor T": "professor-t",
  "Return to Paradise": "return-to-paradise",
  "Sanditon": "sanditon",
  "Sherlock": "sherlock",
  "Sherwood": "sherwood",
  "Shetland": "shetland",
  "Signora Volpe": "signora-volpe",
  "Silent Witness": "silent-witness",
  "The Assassin": "the-assassin",
  "The Chelsea Detective": "the-chelsea-detective",
  "The Durrells in Corfu": "the-durrells-in-corfu",
  "The Gold": "the-gold",
  "Time": "time",
  "Agatha Christie's Tommy & Tuppence": "tommy-and-tuppence",
  "Trespasses": "trespasses",
  "Trigger Point": "trigger-point",
  "Unforgotten": "unforgotten",
  "Vera": "vera",
  "Victoria": "victoria"
};
